In [1]:
import pandas as pd
import numpy as np


In [2]:
# 1. <표 1-4> 소득 5분위별 순자산 보유액 및 점유율 (6 pages)
#15472 25501 36133 50590 100273

#2. 48327 (60대 평균 순 자산)

# 3. 소득 분위별 순 자산 분포
#       소득1분위 2분위 3분위 4분위 5분위
# 자산
# 전 체 100.0 100.0 100.0 100.0 100.0
# 1분위 47.3 28.6 15.7 6.2 2.1
# 2분위 25.6 26.3 25.4 16.6 6.1
# 3분위 14.2 20.6 24.0 27.1 14.1
# 4분위 8.4 15.2 21.3 27.9 27.2
# 5분위 4.5 9.2 13.6 22.2 50.5

# 필요한 초기 자산 구하기

In [3]:
# <표 1-4> 소득 5분위별 순자산 보유액 및 점유율 (6 pages)
avg_asset = np.array([15472, 25501, 36133, 50590, 100273])
avg_asset_prop = avg_asset / 45602 # 45602 = 전체 가구의 평균 순 자산

In [4]:
# 60대의 평균 순자산 기반으로 소득분위별 자산의 비중을 곱해서 60대의 소득분위별 자산의 상대적 금액
avg_asset_60s = 48327 * avg_asset_prop # 60대 가구의 소득분위별 평균 순자산

In [5]:
# 소득 5분위별 순자산 보유액 (60대)
avg_asset_60s

array([ 16396.54716898,  27024.84160782,  38292.16900575,  53613.06368142,
       106264.92853384])

In [6]:
# test
(avg_asset_60s * np.array([0.473, 0.256, 0.142, 0.084, 0.045])).sum()

29396.833394609883

In [7]:
# 소득 분위별 순 자산 분포 * 60대 소득분위별 평균 순자산 = 소득 분위별 60대 평균 순 자산
final_asset_per_income_decile = avg_asset_60s * 10000

In [8]:
final_asset_per_income_decile

array([1.63965472e+08, 2.70248416e+08, 3.82921690e+08, 5.36130637e+08,
       1.06264929e+09])

In [9]:
final_asset_per_income_decile/1300

array([126127.28591526, 207883.39698326, 294555.14619804, 412408.18216475,
       817422.52718336])

# 필요한 withdrawal rate 구할 인컴

In [10]:
# 분위별 소득

avg_income = np.array([1323, 3080, 5036, 7649, 14973]) * 10000 / 12

In [11]:
np.array([1323, 3080, 5036, 7649, 14973])/13*100

array([ 10176.92307692,  23692.30769231,  38738.46153846,  58838.46153846,
       115176.92307692])

In [12]:
avg_income

array([ 1102500.        ,  2566666.66666667,  4196666.66666667,
        6374166.66666667, 12477500.        ])

In [13]:
# https://nps.or.kr/jsppage/info/easy/easy_04_02.jsp
# 소득별 수령액

# 30 35 40

# 1분위 소득 : 597870, 696900, 795930
# 2분위 소득:  824280, 960810, 1097330
# 3분위 소득: 1065780 1242310, 1418830
# 4분위 소득: 1266530, 1476300, 1686080
# 5분위 소득: 1266530, 1476300, 1686080

In [14]:
np.array([597870, 824280, 1065780, 1266530, 1266530])/1300*12

array([ 5518.8       ,  7608.73846154,  9837.96923077, 11691.04615385,
       11691.04615385])

In [15]:
np.array([696900, 960810, 1242310, 1476300, 1476300])/1300*12

array([ 6432.92307692,  8869.01538462, 11467.47692308, 13627.38461538,
       13627.38461538])

In [16]:
np.array([795930, 1097330, 1418830, 1686080, 1686080])/1300*12

array([ 7347.04615385, 10129.2       , 13096.89230769, 15563.81538462,
       15563.81538462])

In [17]:
pension_income_per_decile = np.array([[597870, 696900, 795930],
[824280, 960810, 1097330],
[1065780, 1242310, 1418830],
[1266530, 1476300, 1686080],
[1266530, 1476300, 1686080]])

In [18]:
pension_income_per_decile_80 = np.array([[597870, 696900, 795930],
[824280, 960810, 1097330],
[1065780, 1242310, 1418830],
[1266530, 1476300, 1686080],
[1266530, 1476300, 1686080]])*0.8

In [19]:
pension_income_per_decile_60 = np.array([[597870, 696900, 795930],
[824280, 960810, 1097330],
[1065780, 1242310, 1418830],
[1266530, 1476300, 1686080],
[1266530, 1476300, 1686080]])*0.6

In [21]:
need_for_normal_spending = (2888000 - pension_income_per_decile-520000)*12
need_for_minimum_spending = (2071000 - pension_income_per_decile-520000)*12

In [17]:
need_for_normal_spending_80 = (2888000 - pension_income_per_decile_80)*12
need_for_minimum_spending_80 = (2071000 - pension_income_per_decile_80)*12

In [18]:
need_for_normal_spending_60 = (2888000 - pension_income_per_decile_60)*12
need_for_minimum_spending_60 = (2071000 - pension_income_per_decile_60)*12

In [19]:
need_for_normal_spending

array([[27481560, 26293200, 25104840],
       [24764640, 23126280, 21488040],
       [21866640, 19748280, 17630040],
       [19457640, 16940400, 14423040],
       [19457640, 16940400, 14423040]])

In [20]:
need_for_normal_spending_80

array([[28916448., 27965760., 27015072.],
       [26742912., 25432224., 24121632.],
       [24424512., 22729824., 21035232.],
       [22497312., 20483520., 18469632.],
       [22497312., 20483520., 18469632.]])

In [21]:
need_for_normal_spending_60

array([[30351336., 29638320., 28925304.],
       [28721184., 27738168., 26755224.],
       [26982384., 25711368., 24440424.],
       [25536984., 24026640., 22516224.],
       [25536984., 24026640., 22516224.]])

In [22]:
withdraw_for_normal_spending = need_for_normal_spending.T / final_asset_per_income_decile

In [23]:
withdraw_for_normal_spending_80 = need_for_normal_spending_80.T / final_asset_per_income_decile

In [24]:
withdraw_for_normal_spending_60 = need_for_normal_spending_60.T / final_asset_per_income_decile

In [23]:
withdraw_for_normal_spending

array([[0.12954898, 0.06854671, 0.04080897, 0.02465377, 0.01243838],
       [0.12230136, 0.06248429, 0.03527687, 0.01995857, 0.01006955],
       [0.11505374, 0.05642231, 0.02974509, 0.01526315, 0.0077006 ]])

In [26]:
withdraw_for_normal_spending_80

array([[0.17635693, 0.09895678, 0.06378461, 0.04196237, 0.02117097],
       [0.17055884, 0.09410684, 0.05935894, 0.03820621, 0.0192759 ],
       [0.16476074, 0.08925726, 0.05493351, 0.03444987, 0.01738074]])

In [27]:
withdraw_for_normal_spending_60

array([[0.18510809, 0.10627697, 0.0704645 , 0.04763202, 0.02403143],
       [0.18075952, 0.10263952, 0.06714524, 0.0448149 , 0.02261013],
       [0.17641095, 0.09900233, 0.06382617, 0.04199764, 0.02118876]])

In [24]:
withdraw_for_minimum_spending = need_for_minimum_spending.T / final_asset_per_income_decile

In [25]:
withdraw_for_minimum_spending

array([[ 0.06975591,  0.03226898,  0.01520582,  0.00636718,  0.00321239],
       [ 0.06250828,  0.02620656,  0.00967373,  0.00167198,  0.00084355],
       [ 0.05526066,  0.02014458,  0.00414194, -0.00302344, -0.0015254 ]])

In [30]:
# https://kostat.go.kr/board.es?mid=a10301040300&bid=215&act=view&list_no=422053